"""Initialize business schema and tables using psycopg."""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Iterable

import logging

import psycopg
from psycopg import sql

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import get_settings


LOGGER = logging.getLogger(__name__)


def normalize_psycopg_dsn(database_url: str) -> str:
    """Normalize a database URL for psycopg.

    Args:
        database_url: Raw database URL from settings.

    Returns:
        str: psycopg-compatible database URL.
    """
    if database_url.startswith("postgresql+psycopg://"):
        return database_url.replace("postgresql+psycopg://", "postgresql://", 1)
    if database_url.startswith("postgresql+psycopg2://"):
        return database_url.replace("postgresql+psycopg2://", "postgresql://", 1)
    return database_url


def mask_database_url(database_url: str) -> str:
    """Mask secrets in a database URL for logging.

    Args:
        database_url: Raw database URL.

    Returns:
        str: Masked database URL.
    """
    if "@" not in database_url:
        return database_url
    prefix, suffix = database_url.split("@", 1)
    if "://" not in prefix:
        return database_url
    scheme, userinfo = prefix.split("://", 1)
    if ":" not in userinfo:
        return database_url
    username, _ = userinfo.split(":", 1)
    return f"{scheme}://{username}:***@{suffix}"


def log_server_identity(conn: psycopg.Connection) -> None:
    """Log server identity details.

    Args:
        conn: psycopg connection.
    """
    row = conn.execute(
        """
        SELECT current_database() AS db,
               inet_server_addr() AS addr,
               inet_server_port() AS port,
               current_user AS usr,
               version() AS ver
        """
    ).fetchone()
    data_dir = conn.execute("SHOW data_directory").fetchone()
    if row:
        LOGGER.info(
            "server db=%s addr=%s port=%s user=%s",
            row[0],
            row[1],
            row[2],
            row[3],
        )
        LOGGER.info("server version=%s", row[4])
    if data_dir:
        LOGGER.info("data_directory=%s", data_dir[0])


def execute_statements(
    conn: psycopg.Connection,
    statements: Iterable[sql.SQL],
) -> None:
    """Execute a list of SQL statements.

    Args:
        conn: psycopg connection.
        statements: SQL statements to execute.
    """
    for statement in statements:
        conn.execute(statement)


def build_schema_statements(schema_name: str) -> list[sql.SQL]:
    """Build schema initialization statements.

    Args:
        schema_name: Target schema name.

    Returns:
        list[sql.SQL]: SQL statements to execute.
    """
    schema = sql.Identifier(schema_name)
    return [
        sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(schema),
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_user_id VARCHAR(128) UNIQUE NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        ).format(schema),
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.threads (
                id UUID PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES {}.users(id),
                title VARCHAR(256),
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        ).format(schema, schema),
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                thread_id UUID NOT NULL REFERENCES {}.threads(id),
                role VARCHAR(32) NOT NULL,
                content TEXT NOT NULL,
                tool_payload JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        ).format(schema, schema),
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.artifacts (
                id VARCHAR(64) PRIMARY KEY,
                thread_id UUID NOT NULL REFERENCES {}.threads(id),
                message_id BIGINT NOT NULL REFERENCES {}.messages(id),
                kind VARCHAR(64) NOT NULL,
                media_type VARCHAR(128) NOT NULL,
                storage_path VARCHAR(512) NOT NULL,
                size_bytes BIGINT NOT NULL,
                checksum VARCHAR(128),
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        ).format(schema, schema, schema),
        sql.SQL(
            "CREATE INDEX IF NOT EXISTS ix_threads_user_id_created_at "
            "ON {}.threads (user_id, created_at)"
        ).format(schema),
        sql.SQL(
            "CREATE INDEX IF NOT EXISTS ix_messages_thread_id_created_at "
            "ON {}.messages (thread_id, created_at)"
        ).format(schema),
        sql.SQL(
            "CREATE INDEX IF NOT EXISTS ix_artifacts_thread_id_created_at "
            "ON {}.artifacts (thread_id, created_at)"
        ).format(schema),
    ]


def init_business_schema() -> None:
    """Initialize business schema and tables."""
    settings = get_settings()
    dsn = normalize_psycopg_dsn(settings.database_url)
    LOGGER.info("database_url=%s", mask_database_url(dsn))
    LOGGER.info("business_schema=%s", settings.business_schema)

    statements = build_schema_statements(settings.business_schema)
    with psycopg.connect(dsn) as conn:
        log_server_identity(conn)
        execute_statements(conn, statements)
        schema_exists = conn.execute(
            "SELECT 1 FROM pg_namespace WHERE nspname = %s",
            (settings.business_schema,),
        ).fetchone()
        tables = conn.execute(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = %s
            ORDER BY table_name
            """,
            (settings.business_schema,),
        ).fetchall()
        LOGGER.info("schema_exists=%s", bool(schema_exists))
        LOGGER.info("tables=%s", [row[0] for row in tables])


def main() -> None:
    """Entry point for the initialization script."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    init_business_schema()


if __name__ == "__main__":
    main()
